use_frameworks!

platform :ios, '8.0'

target 'YAXLogining_Example' do
  pod 'YAXLogining', :path => '../'
 pod 'TRUNetworking', :path => '../../TRUNetworking'
  target 'YAXLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
